export const endpoint_errors = {
    "test_groups": "Could not retrieve test group names",
    "execute_q_function": "Error while attempting to execute q function",
    "execute_q_code": "Error while attempting to execute q code",
    "add_test_case": "Could not add test case",
    "edit_test_case": "Could not edit test case",
    "view_test_code": "Could not view test code on kdb server",
    "test_kdb_connection": "Error while attempting to test kdb connection",
    "add_test_group": "Could not add test group",
    "edit_test_group": "Could not edit test group",
    "get_test_group_stats": "Could not retrieve test group pass fail count",
    "get_test_results_30_days": "Could not retrieve test run 30 day summary",
    "get_test_results_by_day": "Could not retrieve test group run results",
    "get_test_result_summary": "Could not retrieve test group details",
    "get_tests_by_ids": "Could not retrieve run data for selected tests",
    "search_tests": "Could not retrieve matching test names",
    "search_functional_tests": "Error while attempting to retrieve matching q function names",
    "get_unique_dates": "Could not retrieve distinct date names",
    "all_functional_tests": "Error while attempting to retrieve all available q functions",
    "get_test_info": "Could not retrieve test info",
    "test_groups": "Could not retrieve test groups",
};
